sudo: required
services:
        - docker


before_install:
        - docker build -t mohitkrishali/docker-react -f Dockerfile.dev .

script:
        - docker run mohitkrishali/docker-react npm run test -- --converage
